### ISSUE TITLE
Supermarket cookbook packaged with .DS_Store file, breaks berks upload

### ISSUE THREAD

**Issue by spajus** [chef-cookbooks/mingw#15]
### Cookbook version
1.2.5

Sorry for skipping the whole questionaire. The issue is that v1.2.5 package in chef supermarket contains `.DS_Store` files, which breaks `berks upload` with following error:

```
E, [2017-02-02T11:39:15.593789 #84505] ERROR -- : Ridley::Errors::HTTPBadRequest: {"error":["Invalid element in array value of 'files'."]}
```

```
$ tar -zxvf mingw.tar.gz
x mingw/.foodcritic
x mingw/README.md
x mingw/CHANGELOG.md
x mingw/CONTRIBUTING.md
x mingw/MAINTAINERS.md
x mingw/metadata.json
x mingw/files/.DS_Store <-- this
x mingw/files/default
x mingw/files/default/bash.bat
x mingw/files/default/custom-upgrade.sh
x mingw/files/default/custom_prefix.sh
x mingw/files/default/pthread.h
x mingw/files/default/time.h
x mingw/libraries/_helper.rb
x mingw/recipes/default.rb
x mingw/resources/get.rb
x mingw/resources/msys2_package.rb
x mingw/resources/tdm_gcc.rb
```

Repackaging an publishing a new cookbook version without .DS_Store would fix the issue.

**Comment by noresjo** [comment]
I've seen this also. The weird thing for me is that if I move the `.berkshelf` to another location on my hard drive it works. Nevertheless, `.DS_Store` should not be part of the package I assume?

**Comment by cheeseplus** [comment]
This has been resolved in 2.x and no longer seems to be an issue.
