### ISSUE TITLE
Compilation failure - NoMethodError

### ISSUE THREAD

**Issue by anirtam** [chef-cookbooks/mingw#5]
================================================================================
Recipe Compile Error in /tmp/d20160517-25782-hzkjzu/cookbooks/mingw/resources/get.rb
================================================================================

NoMethodError
-------------
undefined method `action' for Chef::Resource::MingwGet action provider:Class

Cookbook Trace:
---------------
  /tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:155:in `action'
  /tmp/d20160517-25782-hzkjzu/cookbooks/mingw/resources/get.rb:46:in `class_from_file'
  /tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:41:in `build_from_file'

Relevant File Content:
----------------------
/tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:

148:      end
149:      def self.default_action=(action_name)
150:        default_action action_name
151:      end
152:      def self.action(action, &recipe_block)
153:        action = action.to_sym
154:        declare_action_class
155>>       action_class.action(action, &recipe_block)
156:        self.allowed_actions += [ action ]
157:        default_action action if Array(default_action) == [:nothing]
158:      end
159:      def self.load_current_value(&load_block)
160:        define_method(:load_current_value!, &load_block)
161:      end
162:      def current_value_does_not_exist!
163:        raise Chef::Exceptions::CurrentValueDoesNotExist
164:      end

F
================================================================================
Recipe Compile Error in /tmp/d20160517-25782-hzkjzu/cookbooks/mingw/resources/tdm_gcc.rb
================================================================================

NoMethodError
-------------
undefined method `action' for Chef::Resource::MingwTdmGcc action provider:Class

Cookbook Trace:
---------------
  /tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:155:in `action'
  /tmp/d20160517-25782-hzkjzu/cookbooks/mingw/resources/tdm_gcc.rb:46:in `class_from_file'
  /tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:41:in `build_from_file'

Relevant File Content:
----------------------
/tmp/d20160517-25782-hzkjzu/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:

148:      end
149:      def self.default_action=(action_name)
150:        default_action action_name
151:      end
152:      def self.action(action, &recipe_block)
153:        action = action.to_sym
154:        declare_action_class
155>>       action_class.action(action, &recipe_block)
156:        self.allowed_actions += [ action ]
157:        default_action action if Array(default_action) == [:nothing]
158:      end
159:      def self.load_current_value(&load_block)
160:        define_method(:load_current_value!, &load_block)
161:      end
162:      def current_value_does_not_exist!
163:        raise Chef::Exceptions::CurrentValueDoesNotExist
164:      end

**Comment by tas50** [comment]
This should be resolved with the latest compat_resource cookbook.  Try updating that and feel free to open this back up if you're still having issues.
